#!/usr/bin/env bash

# output commands to help with installing neovim
echo "To install neovim run the following:"
echo "Build it from source https://github.com/neovim/neovim#install-from-source"
echo "$ sudo apt install nodejs npm"
echo "$ sudo apt install ruby-dev"
echo "$ sudo apt install perl"

# Install Plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

mkdir -p ~/.config/nvim/plugin
# mkdir -p ~/.config/nvim/after/plugin
# mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s $(pwd)/$f ~/.config/nvim/$f
done

nvim --headless +PlugInstall +qall
